<script src="cantAssign.js"></script>
<script src="cantAssignCls.js"></script>
<script src="cantAssignObj.js"></script>
<script>
window.addEventListener('load', async(e)=>{
    // 未定義プロパティへの参照・代入禁止
    // オブジェクト
    const obj = cantAssignObj({
        A: {
            a: {
                bool: true,
                int: 1,
                str: 'A',
                fn: ()=>true,
            }
        },
        B: 2,
    })

    try { const E='オブジェクトに存在しないプロパティへの代入を許してしまった！新しくプロパティが生成されてしまった！'; obj.x = E; console.error(E); }
    catch (err) { console.assert('未定義プロパティへの代入禁止: x'===err.message) }

    try { const E='オブジェクトに存在しないプロパティの参照を許してしまった！'; obj.x; console.error(E); }
    catch (err) { console.assert('未定義プロパティへの参照禁止: x'===err.message) }

    console.assert(obj instanceof Object)
    console.assert('Object'===obj.constructor.name)
    console.assert(obj.A.a.bool)
    console.assert(1===obj.A.a.int)
    console.assert('A'===obj.A.a.str)
    console.assert('function'===typeof obj.A.a.fn)
    obj.A.a.int = 2
    console.assert(2===obj.A.a.int)



    // クラス
    class C {
        constructor(v) {this._v = v}
        set v(v) { this._v = v + 1 }
        get v() { return this._v }
    }
    C = cantAssignCls(C)
    const c = new C()

    try { const E='クラスに存在しないプロパティへの代入を許してしまった！新しくプロパティが生成されてしまった！'; C.x = E; console.error(E); }
    catch (err) { console.assert('未定義プロパティへの代入禁止: x'===err.message) }

    try { const E='クラスに存在しないプロパティの参照を許してしまった！'; C.x; console.error(E); }
    catch (err) { console.assert('未定義プロパティへの参照禁止: x'===err.message) }

    try { const E='インスタンスに存在しないプロパティへの代入を許してしまった！新しくプロパティが生成されてしまった！'; c.y = E; console.error(E); }
    catch (err) { console.assert('未定義プロパティへの代入禁止: y'===err.message) }

    try { const E='インスタンスに存在しないプロパティの参照を許してしまった！'; c.y; console.error(E); }
    catch (err) { console.assert('未定義プロパティへの参照禁止: y'===err.message) }

    console.assert(c instanceof C)
    console.assert(undefined===c.v)
    c.v = 1
    console.assert(2===c.v)
    c._v = 3
    console.assert(3===c.v)


})
</script>
